### PR TITLE
remove `go.work` and remove submodule

### PR DESCRIPTION
**Pull request by DeedleFake**
There's a `v0.0.4` release to avoid experimental breakage, but the module in the repo is configured incorrectly. There are _two_ `go.mod` files in the repo, which means that the `pkg` directory is a [submodule](https://go.dev/ref/mod#vcs-dir). Unfortuately, the `v0.0.4` tag applies only to the top-level `go.mod`, not to the module defined by `pkg/go.mod`. Similarly, there's a `go.work` file in the root of the repo, which implies to me that you've been hit by issues from this split moduling as well.

This pull request gets rid of the `go.work` file and removes the submodule. It's too late to fix the `v0.0.4` release, but this should make future releases work correctly. It _is_ however possible to partially fix the `v0.0.4` release by adding [a `pkg/v0.0.4` tag](https://go.dev/ref/mod#vcs-version) for the same commit as the current `v0.0.4` tag. I can't do that with a pull request, though.

### CODE REVIEW

**Comment by diamondburned** [comment]
While it's unfortunate that releases don't play well with submodules, just removing it is not the solution. Use of gotk4/pkg shouldn't require fetching dependencies that are only used for generating code.

I don't agree with removing the submodule.

**Comment by diamondburned** [comment]
The actual fix here is to make a `pkg/0.0.4`. I'll go make that soon, and I'll probably stop versioning the root repository.

**Comment by DeedleFake** [comment]
> Use of gotk4/pkg shouldn't require fetching dependencies that are only used for generating code.

It doesn't. `go.mod` only lists which version of things should be fetched _if_ they're fetched. The actual fetched dependencies are calculated using the `import`s in the actual code.

**Comment by diamondburned** [comment]
I've replaced `v0.0.4` with `pkg/v0.0.4`. This should be fixed now.

**Pull request closed without merging**
