### PR TITLE
Remove github.com/pkg/errors

### PR DESCRIPTION
**Pull request by SevereCloud**
This PR remove [github.com/pkg/errors](https://github.com/pkg/errors)

See [Working with Errors in Go 1.13](https://go.dev/blog/go1.13-errors)

### CODE REVIEW

**Comment by diamondburned** [comment]
What's the reason behind this change? `errors.Wrap` is `Unwrapper`-compliant.

**Comment by SevereCloud** [comment]
`github.com/pkg/errors` largely obsolete by Go 1.13's extended error support

**Comment by diamondburned** [comment]
That doesn't really matter. `pkg/errors` still follows Go 1.13's error
convention, and it's more convenient to use.

**Comment by diamondburned** [comment]
Closing this for the reason above.

**Pull request closed without merging**
